apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.static.name }}
  labels:
    app: {{ .Values.static.name }}
spec:
  replicas: {{ .Values.static.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.static.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.static.name }}
    spec:
      containers:
      - name: cv-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["npm", "run", "serve:static"]
        ports:
        - containerPort: {{ .Values.static.containerPort }}
          name: http
        resources:
          {{- toYaml .Values.static.resources | nindent 10 }}

