apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.english.name }}
  labels:
    app: {{ .Values.english.name }}
spec:
  type: {{ .Values.english.service.type }}
  ports:
  - port: {{ .Values.english.service.port }}
    targetPort: {{ .Values.english.containerPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.english.name }}

